version: '3.3'
services:
    wireguard:
        container_name: wireguard
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Amsterdam
            - SERVERURL=frietpiet.duckdns.org
            - SERVERPORT=51820
            - PEERS=10
            - PEERDNS=auto
        ports:
            - '51820:51820/udp'
        volumes:
            - '/home/pi/wireguard:/config'
            - '/lib/modules:/lib/modules'
        restart: unless-stopped
        image: linuxserver/wireguard
        
      portainer-ce:
        ports:
            - '8000:8000'
            - '9443:9443'
        container_name: portainer
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'portainer_data:/data'
        image: 'portainer/portainer-ce:latest'
